// Generates the sprite sheets, atlas JSONs, CSS sheets and the perk manifest
// from the source icons in assets/iconsource*. Replaces TexturePacker.
//
// Outputs (all gitignored, rebuilt by `npm run sprites` / predev / prebuild):
//   public/sprites/{kill,killcolor,surv,survcolor}-hd.{json,png}  (reel atlases)
//   public/sprites/{kill,surv}-css.{css,png}                      (home grid)
//   src/generated/perks.json                                      (perk name lists)
//
// The numeric filename prefix (NN_camelCase.png) is the perk's index and is
// used as an array position throughout the app, so frames must be emitted in
// numeric order and indices must be contiguous starting at 0.

import { mkdir, readdir, readFile, stat, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import sharp from 'sharp'

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
const SPRITE_DIR = path.join(ROOT, 'public/sprites')
const MANIFEST_PATH = path.join(ROOT, 'src/generated/perks.json')

export const SOURCE_SIZE = 256
export const CSS_SIZE = 128
export const COLUMNS = 16
export const GUTTER = 2

const ICON_NAME = /^(\d+)_[\w-]+\.png$/

const VARIANTS = [
  { atlas: 'kill-hd', dir: 'assets/iconsourceKill' },
  { atlas: 'killcolor-hd', dir: 'assets/iconsourceKillColor' },
  { atlas: 'surv-hd', dir: 'assets/iconsourceSurv' },
  { atlas: 'survcolor-hd', dir: 'assets/iconsourceSurvColor' }
]

const CSS_SHEETS = [
  { sheet: 'kill-css', dir: 'assets/iconsourceKill', spriteClass: 'sprite-killer' },
  { sheet: 'surv-css', dir: 'assets/iconsourceSurv', spriteClass: 'sprite-survivor' }
]

/**
 * "07_bloodhound.png" -> { index: 7, name: "07_bloodhound" }; null when the
 * file doesn't follow the NN_camelCase.png scheme.
 */
export function parseIconName (filename) {
  const m = filename.match(ICON_NAME)
  if (!m) return null
  return { index: parseInt(m[1], 10), name: filename.slice(0, -4) }
}

/**
 * Top-left corner of the icon for a given perk index on a fixed-column grid
 * with a transparent gutter around every cell (avoids sampling bleed when the
 * sheet is drawn scaled).
 */
export function gridLayout (index, cell, { columns = COLUMNS, gutter = GUTTER } = {}) {
  const stride = cell + 2 * gutter
  return {
    x: (index % columns) * stride + gutter,
    y: Math.floor(index / columns) * stride + gutter
  }
}

/** Sheet dimensions for a given icon count. */
export function sheetSize (count, cell, { columns = COLUMNS, gutter = GUTTER } = {}) {
  const stride = cell + 2 * gutter
  return {
    w: Math.min(count, columns) * stride,
    h: Math.ceil(count / columns) * stride
  }
}

/**
 * TexturePacker-compatible atlas JSON: a frames map in numeric perk order
 * (consumed by slotReel.ts via Object.values and by views via Object.keys).
 */
export function buildAtlasJson (names, image) {
  const frames = {}
  for (let i = 0; i < names.length; i++) {
    const { x, y } = gridLayout(i, SOURCE_SIZE)
    frames[names[i]] = {
      frame: { x, y, w: SOURCE_SIZE, h: SOURCE_SIZE },
      rotated: false,
      trimmed: false,
      spriteSourceSize: { x: 0, y: 0, w: SOURCE_SIZE, h: SOURCE_SIZE },
      sourceSize: { w: SOURCE_SIZE, h: SOURCE_SIZE }
    }
  }
  return {
    frames,
    meta: {
      app: 'scripts/build-sprites.mjs',
      version: '1.0',
      image,
      format: 'RGBA8888',
      size: sheetSize(names.length, SOURCE_SIZE),
      scale: '1'
    }
  }
}

/**
 * CSS sprite sheet for the home grid. Selectors must stay `._NN_name` because
 * PerkSwitch.vue builds the class as '_' + perk.name.
 */
export function buildCss (names, spriteClass, image) {
  const lines = [
    '/* generated by scripts/build-sprites.mjs */',
    '',
    `.${spriteClass} {display:inline-block; overflow:hidden; background-repeat: no-repeat;background-image:url(${image});}`,
    ''
  ]
  for (let i = 0; i < names.length; i++) {
    const { x, y } = gridLayout(i, CSS_SIZE)
    lines.push(`._${names[i]} {width:${CSS_SIZE}px; height:${CSS_SIZE}px; background-position: -${x}px -${y}px}`)
  }
  return lines.join('\n') + '\n'
}

/**
 * Scans a source dir, skipping (with a warning) files outside the naming
 * scheme, and returns names sorted by perk index. Throws when indices are
 * missing or duplicated — the index doubles as an array position in the app.
 */
export async function scanIcons (dir) {
  const icons = []
  for (const filename of await readdir(dir)) {
    const parsed = parseIconName(filename)
    if (!parsed) {
      console.warn(`! skipping ${path.join(dir, filename)} (expected NN_camelCase.png)`)
      continue
    }
    icons.push(parsed)
  }
  icons.sort((a, b) => a.index - b.index)
  for (let i = 0; i < icons.length; i++) {
    if (icons[i].index === i) continue
    if (i > 0 && icons[i].index === icons[i - 1].index) {
      throw new Error(`duplicate perk index ${icons[i].index} in ${dir}: ${icons[i - 1].name} and ${icons[i].name}`)
    }
    throw new Error(`missing perk index ${i} in ${dir} (found ${icons[i].name} instead; indices must be contiguous from 0)`)
  }
  return icons.map(i => i.name)
}

async function composeSheet (dir, names, cell, outFile) {
  const ops = await Promise.all(names.map(async (name, i) => {
    const file = path.join(dir, `${name}.png`)
    const { x, y } = gridLayout(i, cell)
    let input = file
    if (cell !== SOURCE_SIZE) {
      input = await sharp(file).resize(cell, cell, { kernel: 'lanczos3' }).toBuffer()
    } else {
      const meta = await sharp(file).metadata()
      if (meta.width !== SOURCE_SIZE || meta.height !== SOURCE_SIZE) {
        throw new Error(`${file} is ${meta.width}x${meta.height}, expected ${SOURCE_SIZE}x${SOURCE_SIZE}`)
      }
    }
    return { input, left: x, top: y }
  }))
  const { w, h } = sheetSize(names.length, cell)
  await sharp({ create: { width: w, height: h, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } })
    .composite(ops)
    // palette PNG (256 colors) — the TexturePacker sheets shipped to production
    // were 8-bit colormap too, and it's ~3x smaller than full RGBA
    .png({ palette: true, compressionLevel: 9 })
    .toFile(outFile)
}

/** True when every output exists, matches the scanned names and is newer than every source. */
async function upToDate (killNames, survNames) {
  const outputs = [
    ...VARIANTS.flatMap(v => [`${v.atlas}.json`, `${v.atlas}.png`]),
    ...CSS_SHEETS.flatMap(c => [`${c.sheet}.css`, `${c.sheet}.png`])
  ].map(f => path.join(SPRITE_DIR, f))
  outputs.push(MANIFEST_PATH)

  let oldestOutput = Infinity
  for (const f of outputs) {
    try {
      oldestOutput = Math.min(oldestOutput, (await stat(f)).mtimeMs)
    } catch {
      return false
    }
  }

  let manifest
  try {
    manifest = JSON.parse(await readFile(MANIFEST_PATH, 'utf8'))
  } catch {
    return false
  }
  if (JSON.stringify(manifest) !== JSON.stringify({ killer: killNames, survivor: survNames })) return false

  let newestSource = (await stat(fileURLToPath(import.meta.url))).mtimeMs
  for (const v of VARIANTS) {
    const dir = path.join(ROOT, v.dir)
    for (const f of await readdir(dir)) {
      newestSource = Math.max(newestSource, (await stat(path.join(dir, f))).mtimeMs)
    }
  }
  return newestSource <= oldestOutput
}

export async function main () {
  const names = {}
  for (const v of VARIANTS) {
    names[v.dir] = await scanIcons(path.join(ROOT, v.dir))
  }
  for (const [gray, color] of [
    ['assets/iconsourceKill', 'assets/iconsourceKillColor'],
    ['assets/iconsourceSurv', 'assets/iconsourceSurvColor']
  ]) {
    const a = names[gray]; const b = names[color]
    if (JSON.stringify(a) !== JSON.stringify(b)) {
      const diff = [...a.filter(n => !b.includes(n)).map(n => `only in ${gray}: ${n}`),
        ...b.filter(n => !a.includes(n)).map(n => `only in ${color}: ${n}`)]
      throw new Error(`gray/color icon sets differ:\n  ${diff.join('\n  ')}`)
    }
  }

  const killNames = names['assets/iconsourceKill']
  const survNames = names['assets/iconsourceSurv']

  if (await upToDate(killNames, survNames)) {
    console.log('sprites up to date')
    return
  }

  await mkdir(SPRITE_DIR, { recursive: true })
  await mkdir(path.dirname(MANIFEST_PATH), { recursive: true })

  for (const v of VARIANTS) {
    await composeSheet(path.join(ROOT, v.dir), names[v.dir], SOURCE_SIZE, path.join(SPRITE_DIR, `${v.atlas}.png`))
    const atlas = buildAtlasJson(names[v.dir], `${v.atlas}.png`)
    await writeFile(path.join(SPRITE_DIR, `${v.atlas}.json`), JSON.stringify(atlas, null, 1) + '\n')
    console.log(`${v.atlas}: ${names[v.dir].length} icons`)
  }

  for (const c of CSS_SHEETS) {
    await composeSheet(path.join(ROOT, c.dir), names[c.dir], CSS_SIZE, path.join(SPRITE_DIR, `${c.sheet}.png`))
    await writeFile(path.join(SPRITE_DIR, `${c.sheet}.css`), buildCss(names[c.dir], c.spriteClass, `${c.sheet}.png`))
    console.log(`${c.sheet}: ${names[c.dir].length} icons`)
  }

  await writeFile(MANIFEST_PATH, JSON.stringify({ killer: killNames, survivor: survNames }, null, 1) + '\n')
  console.log(`manifest: ${killNames.length} killer, ${survNames.length} survivor perks`)
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch(err => {
    console.error(err.message)
    process.exitCode = 1
  })
}
